### ISSUE TITLE
Docker Compose Error

### ISSUE THREAD

**Issue by abdullahcicekli** [jlesage/docker-filezilla#23]
(filezilla:906): WARNING **: 10:45:16.976: invalid source position for vertical gradient

Whats problem ? 

```
filezilla:
        image: jlesage/filezilla
        ports:
            - 21:21
            - 22:22
        volumes:
            - "/docker/appdata/filezilla:/config:rw"
            - "$HOME:/storage:rw"
```
