### ISSUE TITLE
Error 404 Not Found NGINX

### ISSUE THREAD

**Issue by DeltaFox0018** [jlesage/docker-filezilla#24]
I created a docker compose following the one on the github page, the service starts without any problem but when I connect to the web page it gives me error 404 Not Found

Docker composed used

```
version: '3.7'

services:
  filezilla:
    image: jlesage/filezilla
    ports:
      - "5800:5800"
    networks:
      - caddy_16
    volumes:
      - filezillaconfig:/config:rw
      - filezillastorage:/storage:rw
    deploy:
      replicas: 1
      update_config:        
        failure_action: rollback
        parallelism: 1
        # Associato al percorso Caddy             
      labels:        
        caddy2: 'https://domain.test'
        caddy2.reverse_proxy: "{{ upstreams 5800 }}"

networks:
  caddy_16:
    external:
      name: caddy_16

volumes:
  filezillaconfig:
    driver: "cloudstor:azure"
    driver_opts:
      share: filezillaconfig

  filezillastorage:
    driver: "cloudstor:azure"
    driver_opts:
      share: filezillastorage
```
