### ISSUE TITLE
[Bug] Long Blackscreen before display shows content

### ISSUE THREAD

**Issue by the-hotmann** [jlesage/docker-filezilla#56]
### Current Behavior

Similar to this one: https://github.com/jlesage/docker-makemkv/issues/157

I'am having a long (about 10s) blackscreen before the content shows up.
I ofc already tried limiting the `nofile` down to `65536`. But this time It did not work.

I just recently (today) switched back from `ARM64` to `AMD64`. Also keep in mind, that I now run on an `Intel i7 1360p`  which is a `big.LITTLE` CPU and maybe it comes from there, as this might not be supported too well yet?

Everything worked just fine on my Mac Mini M1 and I have the very same data & docker-compose I used there aswell.

### Environment

- OS: Debian SID
- OS version: SID
- CPU: Intel i7 1360p
- Docker version: 24.0.7
- Device model: NUC13ANHi7
- Browser/OS: Chrome v120.0.6099.72

### Container creation

```
  filezilla:
    container_name: filezilla
    image: jlesage/filezilla
    hostname: filezilla
    ports:
      - 5800:5800
    environment:
      - PUID=1026
      - PGID=100
      - DISPLAY_WIDTH=2000
      - DISPLAY_HEIGHT=1200
      - KEEP_APP_RUNNING=1
      - TZ=Europe/Berlin
      - LANG=de_DE.UTF-8
    volumes:
      - "/var/docker/data/filezilla/:/config/:rw"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 1G
    restart: unless-stopped
```

### Container log

```text
    ╭――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╮
    │                                                                      │
    │ Application:           FileZilla                                     │
    │ Application Version:   3.66.1                                        │
    │ Docker Image Version:  23.11.4                                       │
    │ Docker Image Platform: linux/amd64                                   │
    │                                                                      │
    ╰――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╯
[cont-init   ] 89-info.sh: terminated successfully.
[cont-init   ] all container initialization scripts executed.
[init        ] giving control to process supervisor.
[supervisor  ] loading services...
[supervisor  ] loading service 'default'...
[supervisor  ] loading service 'logrotate'...
[supervisor  ] loading service 'app'...
[supervisor  ] loading service 'gui'...
[supervisor  ] loading service 'xvnc'...
[supervisor  ] loading service 'nginx'...
[supervisor  ] loading service 'certsmonitor'...
[supervisor  ] service 'certsmonitor' is disabled.
[supervisor  ] loading service 'openbox'...
[supervisor  ] loading service 'logmonitor'...
[supervisor  ] service 'logmonitor' is disabled.
[supervisor  ] all services loaded.
[supervisor  ] starting services...
[supervisor  ] starting service 'xvnc'...
[xvnc        ] Xvnc TigerVNC 1.13.1 - built Nov 17 2023 22:53:44
[xvnc        ] Copyright (C) 1999-2022 TigerVNC Team and many others (see README.rst)
[xvnc        ] See https://www.tigervnc.org for information on TigerVNC.
[xvnc        ] Underlying X server release 12014000
[xvnc        ] Sat Dec 16 17:45:27 2023
[xvnc        ]  vncext:      VNC extension running!
[xvnc        ]  vncext:      Listening for VNC connections on /tmp/vnc.sock (mode 0660)
[xvnc        ]  vncext:      Listening for VNC connections on all interface(s), port 5900
[xvnc        ]  vncext:      created VNC server for screen 0
[supervisor  ] starting service 'nginx'...
[nginx       ] Listening for HTTP connections on port 5800.
[supervisor  ] starting service 'openbox'...
[supervisor  ] starting service 'app'...
[app         ] Reading locale option from /config/xdg/config/filezilla/filezilla.xml
[supervisor  ] all services started.
[xvnc        ] Sat Dec 16 17:49:34 2023
[xvnc        ]  Connections: accepted: /tmp/vnc.sock
[xvnc        ]  SConnection: Client needs protocol version 3.8
[xvnc        ]  SConnection: Client requests security type None(1)
[xvnc        ]  VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
[xvnc        ]  VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian bgr888
[xvnc        ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
[xvnc        ]  ComparingUpdateTracker: (1:-nan ratio)
```
```


### Container inspect

_No response_

### Anything else?

_No response_
